language: java

before_script:
  - mvn clean

script:
  - mvn compile
  - mvn test

before_deploy:
  - mvn package

deploy:
  provider: cloudfoundry
  username: $PCF_USERNAME
  password: $PCF_PASSWORD
  api: $PCF_API
  organization: $PCF_ORG
  space: $PCF_SPACE
  manifest: manifest.yml # (optional)  Defaults to manifest.yml.
  app_name: ah-poc-papi-springboot # (optional)