server:
  port: ${PORT:8080}

management:
  endpoint:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    health:
      show-details: always

sapis:
  creditCardBalance:
    url: "https://ah-poc-sapi-cc-bal.cfapps.io/customer/{CUSTOMER_ID}/balance"
    health: "https://ah-poc-sapi-cc-bal.cfapps.io/actuator/health"
    info: "https://ah-poc-sapi-cc-bal.cfapps.io/actuator/info"
  currentAccountBalance:
    url: "https://ah-poc-sapi-ca-bal.cfapps.io/customer/{CUSTOMER_ID}/balance"
    health: "https://ah-poc-sapi-ca-bal.cfapps.io/actuator/health"
    info: "https://ah-poc-sapi-ca-bal.cfapps.io/actuator/info"


info:
  dependencies:
    - url: ${sapis.creditCardBalance.info}
    - url: ${sapis.currentAccountBalance.info}